frontend:
  build: frontend
  volumes:
   - frontend:/app
  ports:
    - "8080:80"
  links:
    - projectservice
    - eventsystem

projectservice:
  build: project-service
  command: ../node_modules/gulp/bin/gulp.js project-service:watch
  volumes:
   - project-service:/app
   - node_modules:/node_modules
   - gulp:/gulp
  ports:
   - "3000:80"
  links:
   - postgres
   - eventsystem
  environment:
    AUTH0_SECRET:
    AUTH0_AUDIENCE:
    POSTGRES_USER:
    POSTGRES_PASSWORD:

eventsystem:
  build: event-system
  command: ../node_modules/gulp/bin/gulp.js event-system:watch
  volumes:
   - event-system:/app
   - node_modules:/node_modules
   - gulp:/gulp
  ports:
    - "4000:80"
  links:
    - redis
  environment:
    AUTH0_SECRET:
    AUTH0_AUDIENCE:

postgres:
  image: postgres:latest
  environment:
    POSTGRES_USER:
    POSTGRES_PASSWORD:

redis:
  image: redis:latest
